import { BackupRecord, PitrPlan, PitrTarget, WalSegment } from './types';

export interface PitrValidationResult {
  valid: boolean;
  reason?: string;
  baseBackup?: BackupRecord;
}

export class PitrManager {
  constructor(
    private readonly retentionDays: number = 30,
    private readonly nowProvider: () => Date = () => new Date(),
  ) {}

  /**
   * Validates whether a target PITR timestamp can be safely restored.
   */
  validateTargetTime(
    target: PitrTarget,
    availableBackups: BackupRecord[],
    referenceDate: Date = this.nowProvider(),
  ): PitrValidationResult {
    const targetMs = target.targetTime.getTime();
    const nowMs = referenceDate.getTime();

    if (isNaN(targetMs)) {
      return { valid: false, reason: 'Invalid target timestamp provided' };
    }

    if (targetMs > nowMs) {
      return { valid: false, reason: 'PITR target timestamp cannot be in the future' };
    }

    const maxAgeMs = this.retentionDays * 24 * 60 * 60 * 1000;
    if (nowMs - targetMs > maxAgeMs) {
      return {
        valid: false,
        reason: `Target timestamp is older than the ${this.retentionDays}-day retention window`,
      };
    }

    // Find the latest full or differential backup completed before or at target timestamp
    const eligibleBackups = availableBackups
      .filter((b) => b.completedAt.getTime() <= targetMs)
      .sort((a, b) => b.completedAt.getTime() - a.completedAt.getTime());

    if (eligibleBackups.length === 0) {
      return {
        valid: false,
        reason: 'No completed base backup found prior to target recovery timestamp',
      };
    }

    return {
      valid: true,
      baseBackup: eligibleBackups[0],
    };
  }

  /**
   * Plans the Point-in-Time Recovery sequence.
   */
  createPlan(
    target: PitrTarget,
    availableBackups: BackupRecord[],
    availableWal: WalSegment[],
    referenceDate: Date = this.nowProvider(),
  ): PitrPlan {
    const validation = this.validateTargetTime(target, availableBackups, referenceDate);
    if (!validation.valid || !validation.baseBackup) {
      throw new Error(`PITR planning failed: ${validation.reason}`);
    }

    const baseBackup = validation.baseBackup;
    const baseBackupStartMs = baseBackup.startedAt.getTime();
    const targetMs = target.targetTime.getTime();

    // Select WAL segments covering [baseBackupStart, targetTime]
    const requiredWal = availableWal
      .filter(
        (wal) =>
          wal.archivedAt.getTime() >= baseBackupStartMs &&
          wal.archivedAt.getTime() <= targetMs + 300_000, // include buffer for final transaction
      )
      .sort((a, b) => a.sequence - b.sequence);

    // Verify WAL sequence continuity
    this.verifyWalContinuity(requiredWal);

    // Format recovery configuration for postgresql.auto.conf
    const targetIso = target.targetTime.toISOString().replace('T', ' ').replace('Z', '+00');
    const timeline = target.targetTimeline ?? 'latest';
    const stopInclusive = target.stopInclusive ?? true;

    const recoveryConfig: Record<string, string> = {
      restore_command: "pgbackrest --stanza=verinode archive-get %f '%p'",
      recovery_target_time: `'${targetIso}'`,
      recovery_target_action: "'promote'",
      recovery_target_timeline: typeof timeline === 'number' ? `${timeline}` : `'${timeline}'`,
      recovery_target_inclusive: stopInclusive ? 'true' : 'false',
    };

    // Estimated recovery duration: ~100MB/s base restore + ~5s per WAL segment
    const baseRestoreSec = Math.max(10, Math.ceil(baseBackup.sizeBytes / (100 * 1024 * 1024)));
    const walReplaySec = Math.max(5, requiredWal.length * 3);
    const estimatedDurationSec = baseRestoreSec + walReplaySec;

    return {
      targetTime: target.targetTime,
      baseBackup,
      walSegments: requiredWal,
      estimatedDurationSec,
      recoveryConfig,
      recoverySignalRequired: true,
    };
  }

  /**
   * Checks whether the required WAL sequence has any missing sequence numbers.
   */
  private verifyWalContinuity(walList: WalSegment[]): void {
    if (walList.length <= 1) return;

    for (let i = 1; i < walList.length; i++) {
      const prev = walList[i - 1];
      const curr = walList[i];
      if (curr.sequence !== prev.sequence + 1) {
        throw new Error(
          `WAL sequence discontinuity detected: gap between segment ${prev.sequence} and ${curr.sequence}`,
        );
      }
    }
  }

  /**
   * Serializes recovery config into postgresql.auto.conf string format.
   */
  renderPostgresRecoveryConf(config: Record<string, string>): string {
    return (
      '# Generated by VeriNode PITR Manager\n' +
      Object.entries(config)
        .map(([key, value]) => `${key} = ${value}`)
        .join('\n') +
      '\n'
    );
  }
}
